name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Change directory to spinArrowApp
      run: cd spinArrowApp

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # Updated to use Node.js 18.x

    - name: Install dependencies
      run: |
        cd spinArrowApp
        npm install

    - name: Build the Angular app
      run: |
        cd spinArrowApp
        npm run build --prod --base-href /spinArrowApp/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./spinArrowApp/dist/spin-arrow-app
        publish_branch: gh-pages
        destination_dir: spinArrowApp
