name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        cd spinArrowApp
        npm install

    - name: Build the Angular app (client-side)
      run: |
        cd spinArrowApp
        npx ng build --output-path=dist/spin-arrow-app --base-href /SpinGame/ --configuration production || { echo 'Build failed'; exit 1; }

    - name: List build output
      run: ls -R spinArrowApp/dist

    - name: Check for index.html in build output
      run: |
        if [ -f spinArrowApp/dist/spin-arrow-app/browser/index.html ]; then
          echo "index.html found";
        else
          echo "index.html missing";
          exit 1; # Fail the workflow if index.html is missing
        fi

    - name: Print current directory
      run: pwd

    - name: List files in dist
      run: ls -la spinArrowApp/dist

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: spinArrowApp/dist/spin-arrow-app/browser
        publish_branch: gh-pages
