name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        cd spinArrowApp
        npm install

    - name: Build the Angular app
      run: |
        cd spinArrowApp
        npm run build -- --configuration production --base-href /SpinGame/

    - name: Check for index.html in build output
      run: |
        if [ -f ./spinArrowApp/dist/spin-arrow-app/index.html ]; then echo "index.html found"; else echo "index.html missing"; fi

    - name: List build output
      run: ls -R ./spinArrowApp/dist/spin-arrow-app

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./spinArrowApp/dist/spin-arrow-app
        publish_branch: gh-pages
